#!/usr/bin/env python3
"""
WGC Design System - Multiplatform Token Exporter (Passo 1)
Exports Kotlin core design tokens to JSON, CSS Variables, and iOS Swift tokens.
"""

import os
import json

def export_tokens():
    output_dir = os.path.join(os.path.dirname(__file__), "..", "build", "exported-tokens")
    os.makedirs(output_dir, exist_ok=True)

    tokens = {
        "spacing": {
            "none": "0dp",
            "extraSmall": "4dp",
            "small": "8dp",
            "medium": "16dp",
            "large": "24dp",
            "extraLarge": "32dp",
            "huge": "48dp"
        },
        "radius": {
            "none": "0dp",
            "small": "4dp",
            "medium": "8dp",
            "large": "16dp",
            "pill": "999dp",
            "circular": "1000dp"
        },
        "elevation": {
            "level0": "0dp",
            "level1": "1dp",
            "level2": "3dp",
            "level3": "6dp",
            "level4": "8dp",
            "level5": "12dp"
        },
        "motion": {
            "durationFast": "150ms",
            "durationNormal": "300ms",
            "durationSlow": "500ms"
        }
    }

    # 1. Export JSON Style Dictionary
    json_path = os.path.join(output_dir, "wgc-tokens.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(tokens, f, indent=2)

    # 2. Export CSS Variables
    css_path = os.path.join(output_dir, "wgc-tokens.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(":root {\n")
        for category, values in tokens.items():
            for key, val in values.items():
                f.write(f"  --wgc-{category}-{key}: {val};\n")
        f.write("}\n")

    # 3. Export Swift Tokens for iOS
    swift_path = os.path.join(output_dir, "WgcTokens.swift")
    with open(swift_path, "w", encoding="utf-8") as f:
        f.write("// Generated by WGC Design System Token Exporter\nimport CoreGraphics\n\npublic struct WgcSpacing {\n")
        for key, val in tokens["spacing"].items():
            num = val.replace("dp", "")
            f.write(f"    public static let {key}: CGFloat = {num}\n")
        f.write("}\n\npublic struct WgcRadius {\n")
        for key, val in tokens["radius"].items():
            num = val.replace("dp", "")
            f.write(f"    public static let {key}: CGFloat = {num}\n")
        f.write("}\n")

    print(f"[OK] Tokens exported successfully to {output_dir}")

if __name__ == "__main__":
    export_tokens()
